language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: false  
script:
  - yarn coverage
  - yarn lib
  - yarn build
# after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn coveralls
before_deploy:
  - yarn lib
  - yarn build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: storybook-static
  on:
    branch: master
branches:
  only:
  - master