import { uniqueId } from 'lodash'
import {
  QUESTION_SWITCH,
  QUESTION_TEXT,
  QUESTION_TEXT_AREA,
  QUESTION_RATE,
  QUESTION_DATE,
  QUESTION_DISCRETE_SCALE,
  QUESTION_NUMERICAL_SCALE,
  QUESTION_CHOICES,
  QUESTION_IMAGE,
  QUESTION_RANK,
  QUESTION_CASCADE,
} from '../Types/Question'

export const initialValue = (type) => ({
  [QUESTION_SWITCH]: {
    id: uniqueId(),
    type: QUESTION_SWITCH,
    title: 'Question switch',
    mandatory: false,
    visibleIf: 'true',
    checkedChildren: 'Oui',
    unCheckedChildren: 'Non',
    tooltip: '',
  },
  [QUESTION_TEXT]: {
    id: uniqueId(),
    type: QUESTION_TEXT,
    title: 'Question texte court',
    mandatory: false,
    visibleIf: 'true',
    tooltip: '',
  },
  [QUESTION_TEXT_AREA]: {
    id: uniqueId(),
    type: QUESTION_TEXT_AREA,
    title: 'Question texte long',
    mandatory: false,
    visibleIf: 'true',
    tooltip: '',
  },
  [QUESTION_RATE]: {
    id: uniqueId(),
    type: QUESTION_RATE,
    title: 'Question note',
    mandatory: false,
    visibleIf: 'true',
    tooltip: '',
    count: 5,
  },
  [QUESTION_DATE]: {
    id: uniqueId(),
    type: QUESTION_DATE,
    title: 'Question date',
    mandatory: false,
    visibleIf: 'true',
    tooltip: '',
    dateType: 'date',
    min: '',
    max: '',
  },
  [QUESTION_DISCRETE_SCALE]: {
    id: uniqueId(),
    type: QUESTION_DISCRETE_SCALE,
    title: 'Question échelle discrète',
    mandatory: false,
    visibleIf: 'true',
    tooltip: '',
    min: 0,
    max: 100,
    step: 1,
  },
  [QUESTION_NUMERICAL_SCALE]: {
    id: uniqueId(),
    type: QUESTION_NUMERICAL_SCALE,
    title: 'Question échelle numérique',
    mandatory: false,
    visibleIf: 'true',
    tooltip: '',
    min: 0,
    max: 100,
    step: 1,
    marks: {},
  },
  [QUESTION_CHOICES]: {
    id: uniqueId(),
    type: QUESTION_CHOICES,
    title: 'Question choix multiples',
    mandatory: false,
    visibleIf: 'true',
    tooltip: '',
    choices: [],
    max: 4,
  },
  [QUESTION_IMAGE]: {
    id: uniqueId(),
    type: QUESTION_IMAGE,
    title: 'Question Image',
    mandatory: false,
    visibleIf: 'true',
    tooltip: '',
    maxSize: 10000,
  },
  [QUESTION_RANK]: {
    id: uniqueId(),
    type: QUESTION_RANK,
    title: 'Question rang',
    mandatory: false,
    visibleIf: 'true',
    tooltip: '',
    choices: [],
  },
  [QUESTION_CASCADE]: {
    id: uniqueId(),
    type: QUESTION_CASCADE,
    title: 'Question cascade',
    mandatory: false,
    visibleIf: 'true',
    tooltip: '',
    options: [],
  },
})[type]