import { uniqueId } from 'lodash'
import {
  QUESTION_SWITCH,
  QUESTION_TEXT,
  QUESTION_TEXT_AREA,
  QUESTION_RATE,
  QUESTION_DATE,
  QUESTION_DISCRETE_SCALE,
  QUESTION_NUMERICAL_SCALE,
  QUESTION_CHOICES,
  QUESTION_IMAGE,
  QUESTION_RANK,
} from '../Types/Question'

export const initialValue = (type) => {
  const id = `@@${uniqueId()}`
  return ({
    [QUESTION_SWITCH]: {
      id,
      type: QUESTION_SWITCH,
      title: 'Question switch',
      mandatory: false,
      visibleIf: 'true',
      tooltip: '',
      checkedChildren: 'Oui',
      unCheckedChildren: 'Non',
    },
    [QUESTION_TEXT]: {
      id,
      type: QUESTION_TEXT,
      title: 'Question texte court',
      mandatory: false,
      visibleIf: 'true',
      tooltip: '',
    },
    [QUESTION_TEXT_AREA]: {
      id,
      type: QUESTION_TEXT_AREA,
      title: 'Question texte long',
      mandatory: false,
      visibleIf: 'true',
      tooltip: '',
      autosize: true,
    },
    [QUESTION_RATE]: {
      id,
      type: QUESTION_RATE,
      title: 'Question note',
      mandatory: false,
      visibleIf: 'true',
      tooltip: '',
      max: 5,
    },
    [QUESTION_DATE]: {
      id,
      type: QUESTION_DATE,
      title: 'Question date',
      mandatory: false,
      visibleIf: 'true',
      tooltip: '',
      dateType: 'date',
      min: '',
      max: '',
    },
    [QUESTION_DISCRETE_SCALE]: {
      id,
      type: QUESTION_DISCRETE_SCALE,
      title: 'Question échelle discrète',
      mandatory: false,
      visibleIf: 'true',
      tooltip: '',
      min: 0,
      max: 100,
      step: 1,
    },
    [QUESTION_NUMERICAL_SCALE]: {
      id,
      type: QUESTION_NUMERICAL_SCALE,
      title: 'Question échelle numérique',
      mandatory: false,
      visibleIf: 'true',
      tooltip: '',
      min: 0,
      max: 100,
      step: 1,
      marks: {},
    },
    [QUESTION_CHOICES]: {
      id,
      type: QUESTION_CHOICES,
      title: 'Question choix multiples',
      mandatory: false,
      visibleIf: 'true',
      tooltip: '',
      choices: [],
      max: 4,
    },
    [QUESTION_IMAGE]: {
      id,
      type: QUESTION_IMAGE,
      title: 'Question Image',
      mandatory: false,
      visibleIf: 'true',
      tooltip: '',
      maxSize: 10000,
    },
    [QUESTION_RANK]: {
      id,
      type: QUESTION_RANK,
      title: 'Question rang',
      mandatory: false,
      visibleIf: 'true',
      tooltip: '',
      choices: [],
    }
  })[type]
}