'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
// Actions
var SELECT = exports.SELECT = 'SELECT';

var NEW_SURVEY = exports.NEW_SURVEY = 'NEW_SURVEY';
var SET_SURVEY = exports.SET_SURVEY = 'SET_SURVEY';

var ADD_PAGE = exports.ADD_PAGE = 'ADD_PAGE';
var REMOVE_PAGE = exports.REMOVE_PAGE = 'REMOVE_PAGE';
var SET_PAGE = exports.SET_PAGE = 'SET_PAGE';
var MOVE_PAGE = exports.MOVE_PAGE = 'MOVE_PAGE';

var ADD_QUESTION = exports.ADD_QUESTION = 'ADD_QUESTION';
var REMOVE_QUESTION = exports.REMOVE_QUESTION = 'REMOVE_QUESTION';
var SET_QUESTION = exports.SET_QUESTION = 'SET_QUESTION';
var MOVE_QUESTION = exports.MOVE_QUESTION = 'MOVE_QUESTION';

// Types
var SURVEY = exports.SURVEY = 'SURVEY';
var PAGE = exports.PAGE = 'PAGE';
var QUESTION_TEXT = exports.QUESTION_TEXT = 'QUESTION_TEXT';
var QUESTION_DATE = exports.QUESTION_DATE = 'QUESTION_DATE';
var QUESTION_DISCRETE_SCALE = exports.QUESTION_DISCRETE_SCALE = 'QUESTION_DISCRETE_SCALE';
var QUESTION_NUMERICAL_SCALE = exports.QUESTION_NUMERICAL_SCALE = 'QUESTION_NUMERICAL_SCALE';
var QUESTION_CHOICES = exports.QUESTION_CHOICES = 'QUESTION_CHOICES';
var QUESTION_IMAGE = exports.QUESTION_IMAGE = 'QUESTION_IMAGE';
var QUESTION_RANK = exports.QUESTION_RANK = 'QUESTION_RANK';