'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _Question = require('./Question');

exports.default = {
  QUESTION_SWITCH: _Question.QUESTION_SWITCH,
  QUESTION_TEXT: _Question.QUESTION_TEXT,
  QUESTION_TEXT_AREA: _Question.QUESTION_TEXT_AREA,
  QUESTION_RATE: _Question.QUESTION_RATE,
  QUESTION_DATE: _Question.QUESTION_DATE,
  QUESTION_DISCRETE_SCALE: _Question.QUESTION_DISCRETE_SCALE,
  QUESTION_NUMERICAL_SCALE: _Question.QUESTION_NUMERICAL_SCALE,
  QUESTION_CHOICES: _Question.QUESTION_CHOICES,
  QUESTION_MATRIX: _Question.QUESTION_MATRIX,
  QUESTION_IMAGE: _Question.QUESTION_IMAGE,
  QUESTION_RANK: _Question.QUESTION_RANK
};