// Actions
export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const SET_ITEM = 'SET_ITEM'
export const MOVE_ITEM = 'MOVE_ITEM'

// Types
export const SURVEY = 'SURVEY'
export const PAGE = 'PAGE'
export const QUESTION_TEXT = 'QUESTION_TEXT'
export const QUESTION_DATE = 'QUESTION_DATE'
export const QUESTION_DISCRETE_SCALE = 'QUESTION_DISCRETE_SCALE'
export const QUESTION_NUMERICAL_SCALE = 'QUESTION_NUMERICAL_SCALE'
export const QUESTION_CHOICES = 'QUESTION_CHOICES'
export const QUESTION_IMAGE = 'QUESTION_IMAGE'
export const QUESTION_RANK = 'QUESTION_RANK'