import {
  QUESTION_SWITCH,
  QUESTION_TEXT,
  QUESTION_TEXT_AREA,
  QUESTION_RATE,
  QUESTION_DATE,
  QUESTION_DISCRETE_SCALE,
  QUESTION_NUMERICAL_SCALE,
  QUESTION_CHOICES,
  QUESTION_MATRIX,
  QUESTION_IMAGE,
  QUESTION_RANK,
} from './Question'

export default {
  QUESTION_SWITCH,
  QUESTION_TEXT,
  QUESTION_TEXT_AREA,
  QUESTION_RATE,
  QUESTION_DATE,
  QUESTION_DISCRETE_SCALE,
  QUESTION_NUMERICAL_SCALE,
  QUESTION_CHOICES,
  QUESTION_MATRIX,
  QUESTION_IMAGE,
  QUESTION_RANK,
}